# Generated by Django 5.0.3 on 2024-03-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0002_rename_commentlikes_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images', verbose_name='image'),
        ),
    ]
